fq_dir: ""
work_dir: ""

# pbs Configuration
job:
  name: "wgbs.pbs"
  nodes: 1
  ppn: 20
  shell: "/bin/bash"
  join_output: true
  queue: "slst_pub"
  log_file: "wgbs_pbs_output.log"

# Input Reads
reads:
  - read1: ""  # Provide read1 file path
    read2: ""  # Provide read2 file path if PE, else leave empty

# Strategy
strategy: ""  # Fill in the strategy value

# Environment
conda_env: "base-omics"

# Pipeline Configuration Parameters
trim_params: "--quality 20 --max_n 4 --length 30 --phred33"
cutadapt_params: "-a GGGGGGGGGGGGX -a AGATCGGAAGAG -A AGATCGGAAGAG -A GGGGGGGGGGGGX -g CTCTTCCGATCT -G CTCTTCCGATCT -n 10 --max-n 0.05 -q 20,20 -u -10 -U 10 -m 30 -e 0.2"
bismark_index: "/public/slst/home/qushy/toolkit/reference_genome/index/WGBS-index"
genome_fasta: "/public/slst/home/qushy/toolkit/reference_genome/index/WGBS-index/mm10-lambdaDNA.fa"

# Output Directories
trim_out: "{work_dir}/02_cleandata/trim_galore"
cut_out: "{work_dir}/02_cleandata"
bis_out: "{work_dir}/03_bismark"
dedu_out: "{work_dir}/04_dedu"
extract_out: "{work_dir}/05_extract"
log_dir: "{work_dir}/log"