fq_dir: ""
bismark_strategy: "" #--pbat

# Input Reads
reads:
  - read1: " "  # Provide read1 file path
    read2: " "  # Provide read2 file path if PE, else leave empty

#### 上面部分会通过run.sh提供，只用修改下面的部分 ####

# Spe 为 mm10

# Environment
conda_env: "base-omics"

# Pipeline Configuration Parameters
trim:
  params: "--quality 20 --max_n 4 --length 30 --phred33"
cutadapt:
  pe: "-a GGGGGGGGGGGGX -a AGATCGGAAGAG -A AGATCGGAAGAG -A GGGGGGGGGGGGX -g CTCTTCCGATCT -G CTCTTCCGATCT -n 10 --max-n 0.05 -q 20,20 -u -10 -U 10 -m 30 -e 0.2"
  se: "-a GGGGGGGGGGGGX -a AGATCGGAAGAG -g CTCTTCCGATCT -n 10 --max-n 0.05 -q 20 -u -10 -m 30 -e 0.2"
bismark:
  params: ""
  index: "/public/slst/home/qushy/toolkit/reference_genome/index/WGBS-index"
  genome_fasta_fai: "/public/slst/home/qushy/toolkit/reference_genome/index/WGBS-index/mm10-lambdaDNA.fa.fai"
bis_extractor:
  params: "--gzip --bedGraph --counts --report --comprehensive --multicore 20 --buffer_size 10G"
  #params: "--gzip --bedGraph --counts --report --comprehensive --cytosine_report" # cytosine_report太限速了，也用不上
bw_threshold: "5"
tss_tes:
  repeats: "/home_data/home/slst/leixy2023/data/database/mm10/index_tss_tes/mm10_rep_tss_tes.bed"
  coding_gene: "/home_data/home/slst/leixy2023/data/database/mm10/index_tss_tes/mm10_coding_gene_tss_tes.bed"

